# Generated by Django 4.0.6 on 2022-07-30 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 18, 4, 1, 246406, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
